### ISSUE TITLE
[Feature] Project Setup

### ISSUE THREAD

**Issue by sangrimlee** [woowa-techcamp-2022/web-moneybook-2#1]
## 설명

- 프로젝트를 시작하기 위한 여러가지 설정 적용

## 필요한 작업 내용

- [x] git commit template 적용
- [x] prettier, eslint 적용 (google-style-guide)
- [ ] express 관련 설정
- [x] webpack, babel 관련 설정

## 예상 시간

1시간 15분

**Comment by happyGyu** [comment]
실제 소요시간 express 설정 제외 1시간 15분.
기존의 boiler plate를 가져다 쓰지않고 둘의 스타일을 맞추며 하나하나 적다보니 예상보다 더 걸린 것 같습니다.
